"""Named dimensions for the American Art Deco coffee mug, in millimetres."""

# Cup envelope and drinking cavity. The nominal internal volume is about
# 425 ml before accounting for practical fill height; it is not calibrated.
BODY_HEIGHT = 95.0
BASE_OUTER_RADIUS = 39.0
TOP_OUTER_RADIUS = 44.0
WALL_THICKNESS = 3.2
BASE_THICKNESS = 5.0

# Three stepped octagonal architectural bands around the lower body.
TIER_SIDES = 8
TIER_INNER_RADIUS = 36.5
LOWER_TIER_OUTER_DIAMETER = 90.0
LOWER_TIER_HEIGHT = 5.0
MIDDLE_TIER_OUTER_DIAMETER = 86.0
MIDDLE_TIER_HEIGHT = 5.0
UPPER_TIER_OUTER_DIAMETER = 82.0
UPPER_TIER_HEIGHT = 4.0

# A matching crown band terminates the fluted body below the rim.
CROWN_OUTER_DIAMETER = 91.0
CROWN_INNER_RADIUS = 40.5
CROWN_HEIGHT = 4.0
CROWN_BOTTOM_Z = 82.0

# Vertical flutes make a sunburst-like rhythm around the tapered cup.
FLUTE_COUNT = 12
FLUTE_WIDTH = 2.8
FLUTE_DEPTH = 6.0
FLUTE_HEIGHT = 64.0
FLUTE_CENTER_RADIUS = 42.0
FLUTE_CENTER_Z = 48.0

# Sharply proportioned rectangular Art Deco handle, fused at the right side.
HANDLE_OUTER_WIDTH = 32.0
HANDLE_OUTER_DEPTH = 16.0
HANDLE_OUTER_HEIGHT = 60.0
HANDLE_INNER_WIDTH = 18.0
HANDLE_INNER_HEIGHT = 40.0
HANDLE_CORNER_RADIUS = 2.0
HANDLE_FUSION_OVERLAP = 0.8
HANDLE_CENTER_X = TOP_OUTER_RADIUS + HANDLE_OUTER_WIDTH / 2.0 - HANDLE_FUSION_OVERLAP
HANDLE_CENTER_Z = BODY_HEIGHT / 2.0

EXPECTED_SOLID_COUNT = 1
EXPECTED_OVERALL_WIDTH = CROWN_OUTER_DIAMETER / 2.0 + HANDLE_CENTER_X + HANDLE_OUTER_WIDTH / 2.0
EXPECTED_OVERALL_DEPTH = CROWN_OUTER_DIAMETER
EXPECTED_OVERALL_HEIGHT = BODY_HEIGHT
DIMENSION_TOLERANCE = 0.01
