"""Named dimensions for a full-scale visual reconstruction of a Shure MV6, in mm."""

# Manufacturer-published primary dimensions.
MICROPHONE_LENGTH = 169.0
MICROPHONE_BODY_DIAMETER = 51.0
PUBLISHED_BASE_DIAMETER = 120.0
PUBLISHED_ASSEMBLY_HEIGHT = 295.0

# User-directed proportional refinement after the first reconstruction.
BASE_DIAMETER = 134.0
TARGET_ASSEMBLY_HEIGHT = 275.0
MIC_AXIS_Z = 246.0  # 275 mm target height minus the 29 mm windscreen half-height.
MIC_FRONT_X = -MICROPHONE_LENGTH / 2.0
MIC_REAR_X = MICROPHONE_LENGTH / 2.0

# Foam windscreen: a softly rounded, slightly oversize rectangular capsule.
WINDSCREEN_LENGTH = 70.0
WINDSCREEN_WIDTH = 58.0
WINDSCREEN_HEIGHT = 58.0
WINDSCREEN_SECTION_EXPONENT = 3.4
WINDSCREEN_REAR_X = MIC_FRONT_X + WINDSCREEN_LENGTH
# (X, half-width Y, half-height Z) loft stations inferred across views.
WINDSCREEN_SECTIONS = (
    (MIC_FRONT_X, 24.0, 23.5),
    (MIC_FRONT_X + 5.0, 27.5, 27.0),
    (MIC_FRONT_X + 30.0, 29.0, 29.0),
    (WINDSCREEN_REAR_X - 3.0, 29.0, 29.0),
    (WINDSCREEN_REAR_X, 27.0, 27.0),
)

# Bright collar and dark rear die-cast housing.
COLLAR_LENGTH = 4.0
COLLAR_WIDTH = 54.0
COLLAR_HEIGHT = 54.0
COLLAR_CORNER_RADIUS = 13.0
SHELL_FRONT_X = WINDSCREEN_REAR_X
SHELL_LENGTH = MIC_REAR_X - SHELL_FRONT_X
SHELL_WIDTH = MICROPHONE_BODY_DIAMETER
SHELL_HEIGHT = MICROPHONE_BODY_DIAMETER
SHELL_CORNER_RADIUS = 12.0
SHELL_REAR_EDGE_RADIUS = 4.0
SHELL_SECTION_EXPONENT = 2.65
SHELL_SECTIONS = (
    (SHELL_FRONT_X, 25.5, 25.5),
    (SHELL_FRONT_X + 5.0, 25.5, 25.5),
    (MIC_REAR_X - 7.0, 25.0, 25.0),
    (MIC_REAR_X, 23.2, 23.2),
)

# Four shallow ventilation dimples on each broad side of the shell.
VENT_X_POSITIONS = (-1.5, 62.0)
VENT_Z_OFFSETS = (-15.0, 15.0)
VENT_RADIUS = 4.1
VENT_CUT_DEPTH = 2.6

# Top seam and green capacitive mute button.
TOP_SEAM_WIDTH = 0.65
TOP_SEAM_HEIGHT = 0.45
TOP_SEAM_X_START = -7.5
TOP_SEAM_LENGTH = 73.0
MUTE_BUTTON_CENTER_X = 24.0
MUTE_BUTTON_LENGTH = 17.0
MUTE_BUTTON_WIDTH = 9.5
MUTE_BUTTON_HEIGHT = 1.1
MUTE_BUTTON_RADIUS = 3.8

# Raised side wordmarks. This font is a printable approximation of the logotype.
WORDMARK_TEXT = "SHURE"
WORDMARK_FONT = "DejaVu Sans"
WORDMARK_SIZE = 11.5
WORDMARK_RELIEF = 1.2
WORDMARK_EMBED = 1.3
WORDMARK_CENTER_X = 39.0
WORDMARK_CENTER_Z = MIC_AXIS_Z - 2.0

# Rear connector-face recesses inferred from the rear photograph.
REAR_FACE_INSET = 1.2
USB_PORT_WIDTH = 9.0
USB_PORT_HEIGHT = 3.8
USB_PORT_CENTER_Y = 5.5
USB_PORT_CENTER_Z = MIC_AXIS_Z - 5.0
HEADPHONE_PORT_DIAMETER = 5.8
HEADPHONE_PORT_CENTER_Y = -8.5
HEADPHONE_PORT_CENTER_Z = MIC_AXIS_Z + 5.0

# Weighted desktop stand and post, inferred proportionally then anchored by base size.
STAND_AXIS_X = 17.5
BASE_HEIGHT = 10.0
BASE_EDGE_RADIUS = 2.5
BASE_RECESS_HEIGHT = 1.0
POST_DIAMETER = 17.0
POST_BOTTOM_Z = BASE_HEIGHT - 0.5
POST_TOP_Z = 198.0
POST_COLLAR_BOTTOM_Z = 184.0
POST_COLLAR_HEIGHT = 7.0
POST_COLLAR_DIAMETER = 19.5

# Fork-style tilt mount and underside saddle.
FORK_CENTER_X = STAND_AXIS_X
FORK_OUTER_WIDTH_Y = 31.0
FORK_ARM_THICKNESS = 5.5
FORK_ARM_LENGTH_X = 24.0
FORK_BOTTOM_Z = 187.0
FORK_TOP_Z = 225.0
FORK_CORNER_RADIUS = 6.0
PIVOT_X = STAND_AXIS_X
PIVOT_Z = 209.0
PIVOT_AXLE_RADIUS = 5.0
PIVOT_HEAD_RADIUS = 6.0
PIVOT_HEAD_DEPTH = 1.8
SADDLE_WIDTH_X = 31.0
SADDLE_WIDTH_Y = 20.0
SADDLE_BOTTOM_Z = 207.0
SADDLE_TOP_Z = MIC_AXIS_Z - SHELL_HEIGHT / 2.0 + 1.5
MOUNT_SIDE_CHAMFER = 5.0

# Validation.
EXPECTED_SOLID_COUNT = 1
EXPECTED_OVERALL_WIDTH = MICROPHONE_LENGTH
EXPECTED_OVERALL_DEPTH = BASE_DIAMETER
EXPECTED_OVERALL_HEIGHT = TARGET_ASSEMBLY_HEIGHT
DIMENSION_TOLERANCE = 0.05
